const dummy = [
  {
    "id": 31640,
    "movie_id": 4584,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 114388,
    "overview": "Rich Mr. Dashwood dies, leaving his second wife and her daughters poor by the rules of inheritance. Two daughters are the titular opposites.",
    "popularity": "10.673167",
    "score": 7.7,
    "title": "Sense and Sensibility (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzk1MjU3MDQyMl5BMl5BanBnXkFtZTcwNjc1OTM2MQ@@._V1_UX182_CR0",
    "keywords": "[{'id': 420, 'name': 'bowling'}, {'id': 818, 'name': 'based on novel'}, {'id': 964, 'name': 'servant'}, {'id': 2755, 'name': 'country life'}, {'id': 7564, 'name': 'jane austen'}, {'id': 10911, 'name': 'inheritance'}, {'id': 11109, 'name': 'military officer'}, {'id': 15060, 'name': 'period drama'}, {'id': 156507, 'name': 'rainstorm'}, {'id': 156510, 'name': 'horse and carriage'}, {'id': 156512, 'name': 'decorum'}]"
  },
  {
    "id": 31658,
    "movie_id": 687,
    "genres": "[{'id': 18, 'name': 'Drama'}]",
    "imdb_id": 112818,
    "overview": "A justice drama based on a true story about a man on death row who in his last days forms a strong relationship with a nun who teaches him forgiveness and gives him spirituality as she accompanies him to his execution. Susan Sarandon won an Oscar for best female actress for her convincing portrayal of Sister Helen Prejean.",
    "popularity": "6.891317",
    "score": 7.6,
    "title": "Dead Man Walking (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM3NzA1MjM2N15BMl5BanBnXkFtZTcwMzY3MTMzNA@@._V1_UX182_CR0",
    "keywords": "[{'id': 378, 'name': 'prison'}, {'id': 570, 'name': 'rape'}, {'id': 1952, 'name': 'socially deprived family'}, {'id': 2060, 'name': 'penalty'}, {'id': 2122, 'name': 'death penalty'}, {'id': 2300, 'name': 'despair'}, {'id': 2501, 'name': 'death row'}, {'id': 2538, 'name': 'begnadigung'}, {'id': 2726, 'name': 'therapist'}, {'id': 2796, 'name': 'self-discovery'}, {'id': 2885, 'name': 'prison cell'}, {'id': 3012, 'name': 'court case'}, {'id': 3437, 'name': 'death sentence'}, {'id': 3440, 'name': 'doomed man'}, {'id': 3441, 'name': 'sentence'}, {'id': 3442, 'name': 'lethal injection'}, {'id': 3446, 'name': 'forgiveness'}, {'id': 3447, 'name': 'charity'}, {'id': 3448, 'name': 'mercy petition'}, {'id': 3927, 'name': 'rage and hate'}, {'id': 6059, 'name': 'unsociability'}, {'id': 6145, 'name': 'right and justice'}, {'id': 6148, 'name': 'court'}, {'id': 11263, 'name': 'electric chair'}, {'id': 13001, 'name': 'cowardliness'}]"
  },
  {
    "id": 31668,
    "movie_id": 807,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 114369,
    "overview": "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the \"seven deadly sins\" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
    "popularity": "18.45743",
    "score": 8.6,
    "title": "Se7en (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0",
    "keywords": "[{'id': 476, 'name': 'self-fulfilling prophecy'}, {'id': 703, 'name': 'detective'}, {'id': 1470, 'name': 's.w.a.t.'}, {'id': 2231, 'name': 'drug dealer'}, {'id': 3597, 'name': 'evisceration'}, {'id': 3857, 'name': 'lust and impulsiveness'}, {'id': 3927, 'name': 'rage and hate'}, {'id': 3932, 'name': 'pride and vanity'}, {'id': 4138, 'name': 'immoderateness'}, {'id': 4142, 'name': 'insomnia'}, {'id': 5340, 'name': 'investigation'}, {'id': 6125, 'name': 'pension'}, {'id': 6149, 'name': 'police'}, {'id': 10714, 'name': 'serial killer'}]"
  },
  {
    "id": 31672,
    "movie_id": 11448,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 113819,
    "overview": "When Lenny and his wife, Amanda, adopt a baby, Lenny realizes that his son is a genius and becomes obsessed with finding the boy's biological mother in hopes that she will be brilliant too. But when he learns that Max's mother is Linda Ash, a kindhearted prostitute and porn star, Lenny is determined to reform her immoral lifestyle. A Greek chorus chimes in to relate the plot to Greek mythology in this quirky comedy.",
    "popularity": "15.899134",
    "score": 7.1,
    "title": "Mighty Aphrodite (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMGM1NzM2ZjktNDM5ZS00YmExLTk5ZmYtNDdkNjdkNTdhZWZkXkEyXkFqcGdeQXVyNjE5MjUyOTM@._V1_UX182_CR0",
    "keywords": "[{'id': 549, 'name': 'prostitute'}, {'id': 2393, 'name': 'adoption'}, {'id': 4130, 'name': 'adoptive father'}, {'id': 5885, 'name': 'childlessness'}, {'id': 6230, 'name': 'looking for  birth parents'}, {'id': 8018, 'name': 'adoptive mother'}, {'id': 10183, 'name': 'independent film'}, {'id': 33625, 'name': 'illegal prostitution'}, {'id': 208349, 'name': 'child'}]"
  },
  {
    "id": 31756,
    "movie_id": 649,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 61395,
    "overview": "Beautiful young housewife Séverine Serizy cannot reconcile her masochistic fantasies with her everyday life alongside dutiful husband Pierre. When her lovestruck friend Henri mentions a secretive high-class brothel run by Madame Anais, Séverine begins to work there during the day under the name Belle de Jour. But when one of her clients grows possessive, she must try to go back to her normal life.",
    "popularity": "10.142662",
    "score": 7.8,
    "title": "Belle de Jour (1967)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjhjYWVjZWItZmE3OS00ZTNmLWJhYTktZGM1YWZiNDgxNTU2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR4",
    "keywords": "[{'id': 549, 'name': 'prostitute'}, {'id': 596, 'name': 'adultery'}, {'id': 848, 'name': 'double life'}, {'id': 851, 'name': 'dual identity'}, {'id': 931, 'name': 'jealousy'}, {'id': 1157, 'name': 'wife husband relationship'}, {'id': 1411, 'name': 'brothel'}, {'id': 1566, 'name': 'dream'}, {'id': 2316, 'name': \"women's sexual identity\"}, {'id': 2486, 'name': 'fantasy'}, {'id': 3260, 'name': 'masochism'}, {'id': 10183, 'name': 'independent film'}]"
  },
  {
    "id": 31762,
    "movie_id": 8963,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 112740,
    "overview": "On a US nuclear missile sub, a young first officer stages a mutiny to prevent his trigger happy captain from launching his missiles before confirming his orders to do so.",
    "popularity": "8.657365",
    "score": 7.3,
    "title": "Crimson Tide (1995)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmFkY2IxNTAtMWRiNS00MWU2LWI1NDYtY2YxYTQyYTk5OTBhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 339, 'name': 'submarine'}, {'id': 1860, 'name': 'mutiny'}, {'id': 2139, 'name': 'russia'}, {'id': 2534, 'name': 'missile'}, {'id': 3312, 'name': 'nuclear missile'}, {'id': 4123, 'name': 'embassy'}, {'id': 4410, 'name': 'u.s. navy'}, {'id': 4933, 'name': 'battle for power'}, {'id': 6791, 'name': 'torpedo'}, {'id': 162365, 'name': 'military'}, {'id': 198423, 'name': 'moral dilemma'}, {'id': 217133, 'name': 'post cold war'}, {'id': 221092, 'name': 'aircraft carrier'}, {'id': 226740, 'name': 'chain of command'}, {'id': 226741, 'name': 'launch code'}, {'id': 226742, 'name': 'sonar'}]"
  },
  {
    "id": 31818,
    "movie_id": 2292,
    "genres": "[{'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 109445,
    "overview": "Convenience and video store clerks Dante and Randal are sharp-witted, potty-mouthed and bored out of their minds. So in between needling customers, the counter jockeys play hockey on the roof, visit a funeral home and deal with their love lives.",
    "popularity": "10.513367",
    "score": 7.8,
    "title": "Clerks (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzE1Njk0NmItNDhlMC00ZmFlLWI4ZTUtYTY4ZjgzNjkyMTU1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 1361, 'name': 'salesclerk'}, {'id': 3090, 'name': 'loser'}, {'id': 179430, 'name': 'aftercreditsstinger'}]"
  },
  {
    "id": 31915,
    "movie_id": 1587,
    "genres": "[{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 108550,
    "overview": "Gilbert has to care for his brother Arnie and his obese mother, which gets in the way when love walks into his life.",
    "popularity": "10.3919",
    "score": 7.8,
    "title": "What's Eating Gilbert Grape (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BY2EyZDlhNjItODYzNi00Mzc3LWJjOWUtMTViODU5MTExZWMyL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 380, 'name': 'brother brother relationship'}, {'id': 791, 'name': 'mentally disabled'}, {'id': 2029, 'name': 'iowa'}, {'id': 4129, 'name': 'widow'}, {'id': 10041, 'name': 'dysfunctional family'}, {'id': 10183, 'name': 'independent film'}]"
  },
  {
    "id": 31931,
    "movie_id": 9495,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 109506,
    "overview": "Exactly one year after young rock guitarist Eric Draven and his fiancée are brutally killed by a ruthless gang of criminals, Draven -- watched over by a hypnotic crow -- returns from the grave to exact revenge.",
    "popularity": "15.799336",
    "score": 7.6,
    "title": "The Crow (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Y4ZGVhZjItNjU0OC00MDk1LWI4ZTktYTgwMWJkNDE5OTcxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 3335, 'name': 'halloween'}, {'id': 11363, 'name': 'arson'}, {'id': 18021, 'name': 'detroit'}]"
  },
  {
    "id": 32023,
    "movie_id": 13815,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 109842,
    "overview": "Michael is a 12-year-old drug pusher who lives in a crowded house with his cousins and aunt. His father has become a street bum,but still meets with Fresh on occasion to play chess. Fresh is rather quiet in a crazy world. Fresh's sister is a junkie who sleeps with the dealers that Fresh sells for. As the story progresses Fresh realizes that he doesn't want to sell drugs anymore - he wants revenge.",
    "popularity": "3.970215",
    "score": 7.7,
    "title": "Fresh (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzZjYjE3OTAtYjUzNi00NjA5LThkYzctYWJhZmM5MmNiYjQ3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 1601, 'name': 'war on drugs'}, {'id': 2149, 'name': 'drug traffic'}, {'id': 2231, 'name': 'drug dealer'}, {'id': 2235, 'name': 'drug mule'}, {'id': 5707, 'name': 'childhood trauma'}, {'id': 6691, 'name': 'drug scene'}, {'id': 6712, 'name': 'death of a child'}, {'id': 9748, 'name': 'revenge'}, {'id': 14964, 'name': 'drug'}, {'id': 15155, 'name': 'witness to murder'}, {'id': 34079, 'name': 'death'}]"
  },
  {
    "id": 32024,
    "movie_id": 5503,
    "genres": "[{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}]",
    "imdb_id": 106977,
    "overview": "Wrongfully accused of murdering his wife, Richard Kimble escapes from the law in an attempt to find her killer and clear his name. Pursuing him is a team of U.S. marshals led by Deputy Samuel Gerard, a determined detective who will not rest until Richard is captured. As Richard leads the team through a series of intricate chases, he discovers the secrets behind his wife's death and struggles to expose the killer before it is too late.",
    "popularity": "10.08937",
    "score": 7.8,
    "title": "The Fugitive (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2OTkxNDA2OV5BMl5BanBnXkFtZTgwMzg3MjkyMTE@._V1_UX182_CR0",
    "keywords": "[{'id': 520, 'name': 'chicago'}, {'id': 797, 'name': 'showdown'}, {'id': 1568, 'name': 'undercover'}, {'id': 3262, 'name': 'surgeon'}, {'id': 3437, 'name': 'death sentence'}, {'id': 3440, 'name': 'doomed man'}, {'id': 3442, 'name': 'lethal injection'}, {'id': 3713, 'name': 'chase'}, {'id': 9714, 'name': 'remake'}, {'id': 10085, 'name': 'betrayal'}, {'id': 10562, 'name': 'on the run'}, {'id': 10663, 'name': 'train crash'}, {'id': 10685, 'name': 'escape'}, {'id': 10718, 'name': 'fugitive'}, {'id': 10988, 'name': 'based on tv series'}, {'id': 11207, 'name': 'u.s. marshal'}, {'id': 13005, 'name': 'doctor'}, {'id': 14601, 'name': 'explosion'}, {'id': 14903, 'name': 'home invasion'}, {'id': 18118, 'name': 'disguise'}, {'id': 173976, 'name': 'one armed man'}, {'id': 180172, 'name': 'framed for murder'}, {'id': 187844, 'name': 'flashback'}, {'id': 226376, 'name': 'corrupt cop'}, {'id': 226499, 'name': 'manhunt'}, {'id': 227824, 'name': 'bus accident'}, {'id': 227825, 'name': 'storm drain'}]"
  },
  {
    "id": 32035,
    "movie_id": 11934,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]",
    "imdb_id": 110074,
    "overview": "A naive business graduate is installed as president of a manufacturing company as part of a stock scam.",
    "popularity": "7.550545",
    "score": 7.3,
    "title": "The Hudsucker Proxy (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzNkYzI4ZTYtZjJlZC00ZTVjLTk2MDYtYWMwODA0NmFiYTIwXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 236, 'name': 'suicide'}, {'id': 242, 'name': 'new york'}, {'id': 417, 'name': 'corruption'}, {'id': 736, 'name': 'journalist'}, {'id': 1436, 'name': 'inventor'}, {'id': 1568, 'name': 'undercover'}, {'id': 4290, 'name': 'toy'}, {'id': 4812, 'name': 'plan'}, {'id': 5306, 'name': 'boss'}, {'id': 5340, 'name': 'investigation'}, {'id': 6129, 'name': 'company'}, {'id': 6133, 'name': 'industry'}, {'id': 8508, 'name': 'party'}, {'id': 10594, 'name': 'money'}, {'id': 203525, 'name': 'board'}, {'id': 203528, 'name': 'stocks'}]"
  },
  {
    "id": 32038,
    "movie_id": 9386,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}]",
    "imdb_id": 107206,
    "overview": "Veteran Secret Service agent Frank Horrigan is a man haunted by his failure to save President Kennedy while serving protection detail in Dallas. Thirty years later, a man calling himself \"Booth\" threatens the life of the current President, forcing Horrigan to come back to protection detail to confront the ghosts from his past.",
    "popularity": "12.637158",
    "score": 7.2,
    "title": "In the Line of Fire (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjdhYjRlMTgtNTMzOS00OTZlLWIxMjAtNjM4NGY0NGQxODM3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 591, 'name': 'cia'}, {'id': 782, 'name': 'assassin'}, {'id': 795, 'name': 'running'}, {'id': 833, 'name': 'white house'}, {'id': 840, 'name': 'usa president'}, {'id': 3088, 'name': 'bodyguard'}, {'id': 10333, 'name': 'stalking'}, {'id': 15134, 'name': 'election'}, {'id': 33632, 'name': 'apartment'}, {'id': 41249, 'name': 'secret service'}, {'id': 208633, 'name': 'secret service agent'}]"
  },
  {
    "id": 32067,
    "movie_id": 9300,
    "genres": "[{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}, {'id': 14, 'name': 'Fantasy'}]",
    "imdb_id": 107756,
    "overview": "In 1600, nobleman Orlando inherits his parents' house, thanks to Queen Elizabeth I, who commands the young man to never change. After a disastrous affair with Russian princess Sasha, Orlando looks for solace in the arts before being appointed ambassador to Constantinople in 1700, where war is raging. One morning, Orlando is shocked to wake up as a woman and returns home, struggling as a female to retain her property as the centuries roll by.",
    "popularity": "3.800785",
    "score": 7.2,
    "title": "Orlando (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmY1OTA3MjAtYjQxOC00OTlkLWExZWQtMjc3ZjExOWFhM2UwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_UX182_CR0",
    "keywords": "[{'id': 212, 'name': 'london england'}, {'id': 2011, 'name': 'queen'}, {'id': 7153, 'name': 'queen elizabeth i'}, {'id': 11402, 'name': 'androgyny'}, {'id': 11687, 'name': 'breaking the fourth wall'}, {'id': 177998, 'name': 'nobility'}, {'id': 187056, 'name': 'woman director'}, {'id': 190071, 'name': 'gender bender'}]"
  },
  {
    "id": 32068,
    "movie_id": 9559,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 107808,
    "overview": "A kidnapped boy strikes up a friendship with his captor: an escaped convict on the run from the law, headed by an honorable U.S. Marshal.",
    "popularity": "8.040589",
    "score": 7.5,
    "title": "A Perfect World (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjcyYmU1NzYtMmJiYy00NjJlLWE5ZjMtZWNkOWNjZmQ4MzIyXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_UX182_CR0",
    "keywords": "[{'id': 1562, 'name': 'hostage'}, {'id': 9777, 'name': 'escape from prison'}, {'id': 12414, 'name': 'escaped convict'}, {'id': 170865, 'name': 'child kidnapping'}, {'id': 177609, 'name': 'criminologist'}, {'id': 208992, 'name': '1960s'}]"
  },
  {
    "id": 32069,
    "movie_id": 9800,
    "genres": "[{'id': 18, 'name': 'Drama'}]",
    "imdb_id": 107818,
    "overview": "No one would take his case until one man was willing to take on the system. Two competing lawyers join forces to sue a prestigious law firm for AIDS discrimination. As their unlikely friendship develops their courage overcomes the prejudice and corruption of their powerful adversaries.",
    "popularity": "13.373006",
    "score": 7.7,
    "title": "Philadelphia (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI3NjEwODYyMF5BMl5BanBnXkFtZTgwMzg3ODYxMTE@._V1_UX182_CR0.jpeg",
    "keywords": "[{'id': 237, 'name': 'gay'}, {'id': 740, 'name': 'aids'}, {'id': 1013, 'name': 'homophobia'}, {'id': 1417, 'name': 'jurors'}, {'id': 6148, 'name': 'court'}, {'id': 9104, 'name': 'partner'}, {'id': 9766, 'name': 'hiv'}, {'id': 10909, 'name': 'lawyer'}, {'id': 41589, 'name': 'dying'}, {'id': 186782, 'name': 'discrimination'}, {'id': 207968, 'name': 'judiciary'}]"
  },
  {
    "id": 32088,
    "movie_id": 14291,
    "genres": "[{'id': 18, 'name': 'Drama'}]",
    "imdb_id": 108065,
    "overview": "A prepubescent chess prodigy refuses to harden himself in order to become a champion like the famous but unlikable Bobby Fischer.",
    "popularity": "12.048587",
    "score": 7.5,
    "title": "Searching for Bobby Fischer (1993)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI3NzY3ODg3N15BMl5BanBnXkFtZTcwNzU1NzcyMQ@@._V1_UY268_CR4",
    "keywords": "[{'id': 316, 'name': 'chess'}, {'id': 2348, 'name': 'hustler'}, {'id': 5561, 'name': 'child prodigy'}, {'id': 14512, 'name': 'new york city'}]"
  },
  {
    "id": 32137,
    "movie_id": 812,
    "genres": "[{'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 103639,
    "overview": "Princess Jasmine grows tired of being forced to remain in the palace and she sneaks out into the marketplace  in disguise where she meets street-urchin Aladdin and the two fall in love, although she may only marry a prince. After being thrown in jail, Aladdin and becomes embroiled in a plot to find a mysterious lamp with which the evil Jafar hopes to rule the land.",
    "popularity": "16.357419",
    "score": 8,
    "title": "Aladdin (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI4ODQ1MzAzNV5BMl5BanBnXkFtZTgwMzU4NzMxMDE@._V1_UY268_CR9",
    "keywords": "[{'id': 2343, 'name': 'magic'}, {'id': 4344, 'name': 'musical'}, {'id': 6513, 'name': 'cartoon'}, {'id': 7376, 'name': 'princess'}, {'id': 9673, 'name': 'love'}, {'id': 10267, 'name': 'comedy'}, {'id': 10336, 'name': 'animation'}, {'id': 15149, 'name': 'monkey'}, {'id': 173259, 'name': 'arab'}, {'id': 179430, 'name': 'aftercreditsstinger'}, {'id': 190536, 'name': 'genie'}, {'id': 234183, 'name': 'animal sidekick'}]"
  },
  {
    "id": 32143,
    "movie_id": 408,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}]",
    "imdb_id": 29583,
    "overview": "A beautiful girl, Snow White, takes refuge in the forest in the house of seven dwarfs to hide from her stepmother, the wicked Queen. The Queen is jealous because she wants to be known as \"the fairest in the land,\" and Snow White's beauty surpasses her own.",
    "popularity": "16.263878",
    "score": 7.6,
    "title": "Snow White and the Seven Dwarfs (1937)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwMzE2Mzc4M15BMl5BanBnXkFtZTcwMTE4NTc1Nw@@._V1_UX182_CR0",
    "keywords": "[{'id': 351, 'name': 'poison'}, {'id': 616, 'name': 'witch'}, {'id': 1412, 'name': 'becoming an adult'}, {'id': 1647, 'name': 'sadness'}, {'id': 2011, 'name': 'queen'}, {'id': 2013, 'name': 'attempted murder'}, {'id': 3737, 'name': 'dying and death'}, {'id': 3758, 'name': 'appearance'}, {'id': 7376, 'name': 'princess'}, {'id': 166625, 'name': 'candlelight vigil'}, {'id': 169341, 'name': 'snow white'}]"
  },
  {
    "id": 32194,
    "movie_id": 10363,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 54189,
    "overview": "Tom Ripley is a talented mimic, moocher, forger and all-around criminal improviser; but there's more to Tom Ripley than even he can guess.",
    "popularity": "3.804493",
    "score": 7.8,
    "title": "Purple Noon (1960)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjBlNTIwYWQtYjBmZC00YjhlLWFiMjktMDVjOTlkNmE5NDVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR4",
    "keywords": "[{'id': 383, 'name': 'poker'}, {'id': 544, 'name': 'sailboat'}, {'id': 851, 'name': 'dual identity'}, {'id': 3180, 'name': 'sailing'}, {'id': 4812, 'name': 'plan'}, {'id': 6149, 'name': 'police'}, {'id': 9937, 'name': 'suspense'}, {'id': 33626, 'name': 'millionaire'}, {'id': 155440, 'name': 'hitchcockian'}, {'id': 155845, 'name': 'french noir'}, {'id': 189574, 'name': 'evil man'}, {'id': 209096, 'name': 'forger'}]"
  },
  {
    "id": 32245,
    "movie_id": 21588,
    "genres": "[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}, {'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 109592,
    "overview": "A cemetery man has the unusual problem of the dead rising from the grave. Himself and his assistant must end these creatures' lives again after they are reborn. Everything is going well until \"She\" comes along and stirs things up a bit.",
    "popularity": "6.247819",
    "score": 7.3,
    "title": "Cemetery Man (1994)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmFlMDBmNzEtM2QxNS00MzUyLTk1YTAtZTQ3ODM5YThlOTFhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0",
    "keywords": "[{'id': 6255, 'name': 'insanity'}, {'id': 10327, 'name': 'undead'}, {'id': 11187, 'name': 'grim reaper'}, {'id': 12377, 'name': 'zombie'}, {'id': 162810, 'name': 'macabre'}, {'id': 207769, 'name': 'grotesque'}]"
  },
  {
    "id": 32360,
    "movie_id": 872,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 45152,
    "overview": "In 1927 Hollywood, Don Lockwood and Lina Lamont are a famous on-screen romantic pair in silent movies, but Lina mistakes the on-screen romance for real love. When their latest film is transformed into a musical, Don has the perfect voice for the songs, but strident voice faces the studio to dub her voice. Aspiring actress, Kathy Selden is brought in and, while she is working on the movie, Don falls in love with her.",
    "popularity": "11.064858",
    "score": 8.3,
    "title": "Singin' in the Rain (1952)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDRjNGViMjQtOThlMi00MTA3LThkYzQtNzJkYjBkMGE0YzE1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UY268_CR0",
    "keywords": "[{'id': 3177, 'name': 'fan'}, {'id': 3748, 'name': 'morning'}, {'id': 4344, 'name': 'musical'}, {'id': 6494, 'name': 'talkie'}, {'id': 9104, 'name': 'partner'}, {'id': 9732, 'name': 'movie in movie'}, {'id': 156028, 'name': 'broadway'}, {'id': 164090, 'name': 'audience'}, {'id': 164623, 'name': 'chorus girl'}, {'id': 164628, 'name': 'diction coach'}, {'id': 164636, 'name': 'pearl necklace'}, {'id': 164641, 'name': 'flapper'}]"
  },
  {
    "id": 32365,
    "movie_id": 567,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 47396,
    "overview": "Professional photographer L.B. \"Jeff\" Jeffries breaks his leg while getting an action shot at an auto race. Confined to his New York apartment, he spends his time looking out of the rear window observing the neighbors. He begins to suspect that a man across the courtyard may have murdered his wife. Jeff enlists the help of his high society fashion-consultant girlfriend Lisa Freemont and his visiting nurse Stella to investigate.",
    "popularity": "17.911314",
    "score": 8.5,
    "title": "Rear Window (1954)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0",
    "keywords": "[{'id': 428, 'name': 'nurse'}, {'id': 1003, 'name': 'photographer'}, {'id': 2619, 'name': 'suspicion of murder'}, {'id': 5490, 'name': 'girlfriend'}, {'id': 10226, 'name': 'neighbor'}, {'id': 10332, 'name': 'salesman'}, {'id': 33632, 'name': 'apartment'}, {'id': 160967, 'name': 'convalescence'}, {'id': 178649, 'name': 'voyeurism'}, {'id': 236909, 'name': 'homebound'}]"
  },
  {
    "id": 32371,
    "movie_id": 239,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 53291,
    "overview": "Two musicians witness a mob hit and struggle to find a way out of the city before they are found by the gangsters. Their only opportunity is to join an all-girl band as they leave on a tour. To make their getaway they must first disguise themselves as women, then keep their identities secret and deal with the problems this brings - such as an attractive bandmate and a very determined suitor.",
    "popularity": "11.845107",
    "score": 8.3,
    "title": "Some Like It Hot (1959)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0",
    "keywords": "[{'id': 520, 'name': 'chicago'}, {'id': 3581, 'name': 'witness'}, {'id': 4048, 'name': 'musician'}, {'id': 10391, 'name': 'mafia'}, {'id': 12090, 'name': 'cross dressing'}, {'id': 33624, 'name': 'band'}, {'id': 160395, 'name': 'spats'}, {'id': 160396, 'name': 'all girl band'}, {'id': 160397, 'name': \"st. valentine's day massacre\"}, {'id': 160400, 'name': 'sugar'}, {'id': 160404, 'name': \"valentine's day\"}, {'id': 160406, 'name': 'dressing'}]"
  },
  {
    "id": 32391,
    "movie_id": 303,
    "genres": "[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 38787,
    "overview": "Released shortly after the war, this classic Hitchcock film illustrates the battle between German Nazis and American spies in Rio de Janeiro where a German businessman keeps a wine cellar with uranium ore.",
    "popularity": "10.135111",
    "score": 8,
    "title": "Notorious (1946)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYTc1NGViOTMtNjZhNS00OGY2LWI4MmItOWQwNTY4MDMzNWI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0",
    "keywords": "[{'id': 351, 'name': 'poison'}, {'id': 699, 'name': 'love at first sight'}, {'id': 1459, 'name': 'marriage proposal'}, {'id': 1568, 'name': 'undercover'}, {'id': 1627, 'name': 'patriotism'}, {'id': 1809, 'name': 'rio de janeiro'}, {'id': 1811, 'name': 'wine cellar'}, {'id': 1812, 'name': 'fbi'}, {'id': 1815, 'name': 'atomic bomb'}, {'id': 1816, 'name': 'staircase'}, {'id': 2652, 'name': 'nazis'}, {'id': 5600, 'name': 'daughter'}, {'id': 9937, 'name': 'suspense'}, {'id': 11134, 'name': 'espionage'}, {'id': 33626, 'name': 'millionaire'}, {'id': 155718, 'name': 'intoxication'}, {'id': 195402, 'name': 'film noir'}]"
  },
  {
    "id": 32396,
    "movie_id": 29376,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}]",
    "imdb_id": 45537,
    "overview": "A pretentiously artistic director is hired for a new Broadway musical and changes it beyond recognition.",
    "popularity": "3.573935",
    "score": 7.6,
    "title": "The Band Wagon (1953)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxZmJkZTgtMmI1Ny00Mzg3LWFlY2QtMjNkM2QwZGVhYTQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0",
    "keywords": "[{'id': 33681, 'name': 'top hat'}, {'id': 33934, 'name': 'choreographer'}, {'id': 187256, 'name': 'ballerina'}]"
  },
  {
    "id": 32402,
    "movie_id": 32093,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}, {'id': 37, 'name': 'Western'}]",
    "imdb_id": 32762,
    "overview": "Around 1820 the son of a California nobleman comes home from Spain to find his native land under a villainous dictatorship. On the one hand he plays the useless fop, while on the other he is the masked avenger Zorro.",
    "popularity": "7.431939",
    "score": 7.6,
    "title": "The Mark of Zorro (1940)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2ODc0NzUyMl5BMl5BanBnXkFtZTgwODQ3NTA1MjE@._V1_UX182_CR0",
    "keywords": "[{'id': 232481, 'name': 'zorro'}]"
  },
  {
    "id": 32432,
    "movie_id": 261,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 51459,
    "overview": "Brick, an alcoholic ex-football player, drinks his days away and resists the affections of his wife, Maggie. His reunion with his father, Big Daddy, who is dying of cancer, jogs a host of memories and revelations for both father and son.",
    "popularity": "11.794846",
    "score": 8.1,
    "title": "Cat on a Hot Tin Roof (1958)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzFhNTMwNDMtZjY3Yy00NzY3LWI1ZWQtZTQxMWJmODVhZWFkXkEyXkFqcGdeQXVyNjQzNDI3NzY@._V1_UX182_CR0",
    "keywords": "[{'id': 30, 'name': 'individual'}, {'id': 236, 'name': 'suicide'}, {'id': 531, 'name': 'southern usa'}, {'id': 596, 'name': 'adultery'}, {'id': 787, 'name': 'mississippi'}, {'id': 894, 'name': 'depression'}, {'id': 931, 'name': 'jealousy'}, {'id': 1157, 'name': 'wife husband relationship'}, {'id': 3737, 'name': 'dying and death'}, {'id': 33457, 'name': 'alcoholic'}]"
  },
  {
    "id": 32514,
    "movie_id": 31530,
    "genres": "[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 29546,
    "overview": "Ballet star Pete \"Petrov\" Peters arranges to cross the Atlantic aboard the same ship as the dancer he's fallen for but barely knows, musical star Linda Keene. By the time the ocean liner reaches New York, a little white lie has churned through the rumor mill and turned into a hot gossip item: that the two celebrities are secretly married.",
    "popularity": "3.786353",
    "score": 7.6,
    "title": "Shall We Dance (1937)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTdhZDE3N2ItZjY3Mi00Y2RkLWE5MGUtNDdmMWQ4OGFhZGUyXkEyXkFqcGdeQXVyNDQzMDg4Nzk@._V1_UX182_CR0",
    "keywords": "[{'id': 4118, 'name': 'ballet dancer'}, {'id': 4344, 'name': 'musical'}]"
  },
  {
    "id": 32448,
    "movie_id": 1770,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 117039,
    "overview": "Michael Collins plays a crucial role in the establishment of the Irish Free State in the 1920s, but becomes vilified by those hoping to create a completely independent Irish republic.",
    "popularity": "6.728199",
    "score": 7.1,
    "title": "Michael Collins (1996)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE4MDE0MjEzMl5BMl5BanBnXkFtZTcwNjc1MzkxMQ@@._V1_UY268_CR7",
    "keywords": "[{'id': 393, 'name': 'civil war'}, {'id': 1721, 'name': 'fight'}, {'id': 2946, 'name': 'presidential election'}, {'id': 3538, 'name': 'freedom fighter'}, {'id': 4355, 'name': 'chinese civil war'}, {'id': 14985, 'name': 'ireland'}]"
  },
  {
    "id": 32540,
    "movie_id": 9504,
    "genres": "[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}]",
    "imdb_id": 104348,
    "overview": "Glengarry Glen Ross, follows the lives of four unethical Chicago real estate agents who are prepared to go to any lengths (legal or illegal) to unload undesirable real estate on unwilling prospective buyers.",
    "popularity": "6.792215",
    "score": 7.8,
    "title": "Glengarry Glen Ross (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzgzYWY0NTUtZTYyMS00NmFhLWIzNjItNzQ5Mzc1YTE5OWM0XkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0",
    "keywords": "[{'id': 642, 'name': 'robbery'}, {'id': 1438, 'name': 'office'}, {'id': 1998, 'name': 'shop'}, {'id': 2918, 'name': 'estate agent'}, {'id': 6129, 'name': 'company'}, {'id': 11836, 'name': 'contest'}, {'id': 13001, 'name': 'cowardliness'}, {'id': 34117, 'name': 'cult film'}, {'id': 179867, 'name': 'real estate'}, {'id': 201885, 'name': 'pressure'}, {'id': 207268, 'name': 'neo-noir'}]"
  },
  {
    "id": 32541,
    "movie_id": 15764,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 84707,
    "overview": "Meryl Streep stars as Sophie, a Polish immigrant who shares a boarding house in Brooklyn with her tempestuous lover, Nathan (Kevin Kline in his feature film debut), and a young writer, Stingo (Peter MacNicol).",
    "popularity": "15.417202",
    "score": 7.7,
    "title": "Sophie's Choice (1982)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3NDUyYTEtMzkyZi00YjMzLTkwMDUtYWMzNjIwNmM5NWQ5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 242, 'name': 'new york'}, {'id': 1631, 'name': 'concentration camp'}, {'id': 1739, 'name': 'holocaust'}, {'id': 13028, 'name': 'writer'}]"
  },
  {
    "id": 32560,
    "movie_id": 11816,
    "genres": "[{'id': 18, 'name': 'Drama'}]",
    "imdb_id": 82846,
    "overview": "The loons are back again on Golden Pond and so are Norman Thayer, a retired professor, and Ethel who have had a summer cottage there since early in their marriage. This summer their daughter Chelsea -- whom they haven't seen for years -- feels she must be there for Norman's birthday. She and her fiance are on their way to Europe the next day but will be back in a couple of weeks to pick up the fiance's son. When she returns Chelsea is married and her stepson has the relationship with her father that she always wanted. Will father and daughter be able to communicate at last?",
    "popularity": "12.252186",
    "score": 7.7,
    "title": "On Golden Pond (1981)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWQ4MGZlZmYtZjY0MS00N2JhLWE0NmMtOTMwMTk4NDQ4NjE2XkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_UX182_CR0",
    "keywords": "[{'id': 5153, 'name': 'son'}, {'id': 5600, 'name': 'daughter'}, {'id': 10707, 'name': 'mother daughter relationship'}, {'id': 33694, 'name': 'family holiday'}, {'id': 155294, 'name': 'family conflict'}]"
  },
  {
    "id": 32614,
    "movie_id": 2493,
    "genres": "[{'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}, {'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",
    "imdb_id": 93779,
    "overview": "In this enchantingly cracked fairy tale, the beautiful Princess Buttercup and the dashing Westley must overcome staggering odds to find happiness amid six-fingered swordsmen, murderous princes, Sicilians and rodents of unusual size. But even death can't stop these true lovebirds from triumphing.",
    "popularity": "15.15267",
    "score": 8.1,
    "title": "The Princess Bride (1987)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMGM4M2Q5N2MtNThkZS00NTc1LTk1NTItNWEyZjJjNDRmNDk5XkEyXkFqcGdeQXVyMjA0MDQ0Mjc@._V1_UX182_CR0",
    "keywords": "[{'id': 157186, 'name': 'swashbuckler'}, {'id': 160350, 'name': 'evil prince'}, {'id': 160358, 'name': 'reference to socrates'}, {'id': 160359, 'name': 'reference to plato'}, {'id': 160362, 'name': 'screwball'}, {'id': 160364, 'name': 'impersonation'}]"
  },
  {
    "id": 32621,
    "movie_id": 947,
    "genres": "[{'id': 12, 'name': 'Adventure'}, {'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}]",
    "imdb_id": 56172,
    "overview": "An epic about British officer T.E. Lawrence's mission to aid the Arab tribes in their revolt against the Ottoman Empire during the First World War. Lawrence becomes a flamboyant, messianic figure in the cause of Arab unity but his psychological instability threatens to undermine his achievements.",
    "popularity": "10.893332",
    "score": 8.3,
    "title": "Lawrence of Arabia (1962)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UY268_CR2",
    "keywords": "[{'id': 487, 'name': 'cairo'}, {'id': 1975, 'name': 'arabian'}, {'id': 2504, 'name': 'world war i'}, {'id': 2673, 'name': 'horse'}, {'id': 3575, 'name': 'jerusalem'}, {'id': 4100, 'name': 'british army'}, {'id': 4107, 'name': 'british empire'}, {'id': 4535, 'name': 'damascus'}, {'id': 4717, 'name': 'camel'}, {'id': 6091, 'name': 'war'}, {'id': 18034, 'name': 'desert'}, {'id': 173259, 'name': 'arab'}, {'id': 214410, 'name': 'ottoman empire'}]"
  },
  {
    "id": 32624,
    "movie_id": 28,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}]",
    "imdb_id": 78788,
    "overview": "At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, \"does not exist, nor will it ever exist.\" His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.",
    "popularity": "13.5963",
    "score": 8.5,
    "title": "Apocalypse Now (1979)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODViM2VjYWYtMzU5Ny00ZjczLWEzNjMtODZmNGMwZDAxNzJkXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_UX182_CR0",
    "keywords": "[{'id': 1008, 'name': 'guerrilla'}, {'id': 1261, 'name': 'river'}, {'id': 2956, 'name': 'vietnam'}, {'id': 2959, 'name': 'vietcong'}, {'id': 2960, 'name': 'cambodia'}, {'id': 6092, 'name': 'army'}, {'id': 6255, 'name': 'insanity'}, {'id': 10148, 'name': 'tribe'}, {'id': 10403, 'name': 'green beret'}, {'id': 10787, 'name': 'jungle'}, {'id': 12332, 'name': 'apocalypse'}, {'id': 34079, 'name': 'death'}, {'id': 177275, 'name': 'napalm'}]"
  },
  {
    "id": 32630,
    "movie_id": 348,
    "genres": "[{'id': 27, 'name': 'Horror'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 878, 'name': 'Science Fiction'}]",
    "imdb_id": 78748,
    "overview": "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
    "popularity": "23.37742",
    "score": 8.5,
    "title": "Alien (1979)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDNhN2IxZWItNGEwYS00ZDNhLThiM2UtODU3NWJlZjBkYjQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0",
    "keywords": "[{'id': 803, 'name': 'android'}, {'id': 1825, 'name': 'countdown'}, {'id': 1826, 'name': 'space marine'}, {'id': 1828, 'name': 'space suit'}, {'id': 1829, 'name': 'beheading'}, {'id': 4565, 'name': 'dystopia'}, {'id': 6016, 'name': 'biology'}, {'id': 7956, 'name': 'cowardice'}, {'id': 9831, 'name': 'spaceship'}, {'id': 9882, 'name': 'space'}, {'id': 9951, 'name': 'alien'}, {'id': 11322, 'name': 'female protagonist'}, {'id': 12405, 'name': 'outer space'}, {'id': 157634, 'name': 'parasite'}, {'id': 181034, 'name': 'h. r. giger'}, {'id': 226177, 'name': 'xenomorph'}]"
  },
  {
    "id": 32634,
    "movie_id": 10835,
    "genres": "[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 97202,
    "overview": "Mob assassin Jeffrey is no ordinary hired gun; the best in his business, he views his chosen profession as a calling rather than simply a job. So, when beautiful nightclub chanteuse Jennie is blinded in the crossfire of his most recent hit, Jeffrey chooses to retire after one last job to pay for his unintended victim's sight-restoring operation. But when Jeffrey is double-crossed, he reluctantly joins forces with a rogue policeman to make things right.",
    "popularity": "8.019837",
    "score": 7.9,
    "title": "The Killer (1989)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDQyMDVhZjItMGI0Mi00MDQ1LTk3NmQtZmRjZGQ5ZTQ2ZDU5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX182_CR0",
    "keywords": "[{'id': 1741, 'name': 'blindness and impaired vision'}, {'id': 2708, 'name': 'hitman'}, {'id': 6149, 'name': 'police'}, {'id': 12354, 'name': 'hong kong'}]"
  },
  {
    "id": 32635,
    "movie_id": 539,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 54215,
    "overview": "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.",
    "popularity": "36.826309",
    "score": 8.5,
    "title": "Psycho (1960)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDI3OWRmOTEtOWJhYi00N2JkLTgwNGItMjdkN2U0NjFiZTYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 612, 'name': 'hotel'}, {'id': 1443, 'name': 'clerk'}, {'id': 1859, 'name': 'arizona'}, {'id': 1879, 'name': 'shower'}, {'id': 2217, 'name': 'rain'}, {'id': 2669, 'name': 'motel'}, {'id': 10594, 'name': 'money'}, {'id': 11677, 'name': 'secretary'}, {'id': 13092, 'name': 'corpse'}, {'id': 13112, 'name': 'murderer'}, {'id': 14604, 'name': 'theft'}, {'id': 155790, 'name': 'private detective'}, {'id': 233450, 'name': 'proto-slasher'}]"
  },
  {
    "id": 32636,
    "movie_id": 525,
    "genres": "[{'id': 10402, 'name': 'Music'}, {'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}]",
    "imdb_id": 80455,
    "overview": "Jake Blues is just out of jail, and teams up with his brother, Elwood on a 'mission from God' to raise funds for the orphanage in which they grew up. The only thing they can do is do what they do best – play music – so they get their old band together and they're on their way, while getting in a bit of trouble here and there.",
    "popularity": "10.076901",
    "score": 7.9,
    "title": "The Blues Brothers (1980)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzdhOTJmYmQtMmE0OS00ZDMyLWFkZDItZmZmMGJlNGUyNjNhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0",
    "keywords": "[{'id': 246, 'name': 'dancing'}, {'id': 378, 'name': 'prison'}, {'id': 520, 'name': 'chicago'}, {'id': 727, 'name': 'country music'}, {'id': 745, 'name': 'nun'}, {'id': 1416, 'name': 'jazz'}, {'id': 1926, 'name': 'car journey'}, {'id': 2636, 'name': 'blues'}, {'id': 2652, 'name': 'nazis'}, {'id': 6027, 'name': 'music'}, {'id': 6029, 'name': 'concert'}, {'id': 6031, 'name': 'music instrument'}, {'id': 6272, 'name': \"children's home\"}, {'id': 6490, 'name': 'shopping mall'}, {'id': 6783, 'name': 'orphanage'}, {'id': 11313, 'name': 'winnebago'}, {'id': 14765, 'name': 'church'}, {'id': 15211, 'name': 'sunglasses'}, {'id': 15232, 'name': 'parole'}, {'id': 15483, 'name': 'car chase'}, {'id': 41591, 'name': 'music band'}, {'id': 156336, 'name': 'loudspeaker'}, {'id': 167213, 'name': 'saturday night live'}, {'id': 226464, 'name': 'wrigley field'}, {'id': 226465, 'name': 'holiday inn'}]"
  },
  {
    "id": 32655,
    "movie_id": 763,
    "genres": "[{'id': 27, 'name': 'Horror'}, {'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 103873,
    "overview": "When a Sumatran rat-monkey bites Lionel Cosgrove's mother, she's transformed into a zombie and begins killing (and transforming) the entire town while Lionel races to keep things under control.",
    "popularity": "13.645568",
    "score": 7.6,
    "title": "Braindead (1992)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2ODI4NjYxOF5BMl5BanBnXkFtZTgwODU0ODgwNzE@._V1_UX182_CR0",
    "keywords": "[{'id': 351, 'name': 'poison'}, {'id': 2658, 'name': 'new zealand'}, {'id': 10122, 'name': 'reanimation'}, {'id': 11097, 'name': 'part stop motion'}, {'id': 11513, 'name': 'cheating husband'}, {'id': 12377, 'name': 'zombie'}, {'id': 12415, 'name': 'back from the dead'}, {'id': 15149, 'name': 'monkey'}, {'id': 18087, 'name': 'attempted rape'}, {'id': 157444, 'name': 'dismemberment'}, {'id': 157624, 'name': 'nagging mother'}, {'id': 157626, 'name': 'director cameo'}]"
  },
  {
    "id": 32664,
    "movie_id": 826,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}]",
    "imdb_id": 50212,
    "overview": "The classic story of English POWs in Burma forced to build a bridge to aid the war effort of their Japanese captors. British and American intelligence officers conspire to blow up the structure, but Col. Nicholson , the commander who supervised the bridge's construction, has acquired a sense of pride in his creation and tries to foil their plans.",
    "popularity": "8.851646",
    "score": 8.2,
    "title": "The Bridge on the River Kwai (1957)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYjE1MzU4NWEtYjhjZS00NzM3LWIyYjQtMWU1M2VkNWYzMzMwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0",
    "keywords": "[{'id': 233, 'name': 'japan'}, {'id': 836, 'name': 'resistance'}, {'id': 907, 'name': 'japanese'}, {'id': 1261, 'name': 'river'}, {'id': 1968, 'name': 'prisoners of war'}, {'id': 3434, 'name': 'thailand'}, {'id': 3450, 'name': 'bridge'}, {'id': 3776, 'name': 'officer'}]"
  },
  {
    "id": 32667,
    "movie_id": 828,
    "genres": "[{'id': 18, 'name': 'Drama'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 43456,
    "overview": "An alien and a robot land on earth after World War II and tell mankind to be peaceful or face destruction. A classic science fiction film from Robert Wise with an exceptional message.",
    "popularity": "9.360003",
    "score": 7.8,
    "title": "The Day the Earth Stood Still (1951)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYjUzNGQ0ZTUtNjMzNy00YmFjLTg2NjctM2UwODUzZGZlNDhhXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UY268_CR3",
    "keywords": "[{'id': 1612, 'name': 'spacecraft'}, {'id': 3243, 'name': 'flying saucer'}, {'id': 6057, 'name': 'peace'}, {'id': 8506, 'name': 'remote control'}, {'id': 9738, 'name': 'ufo'}, {'id': 10891, 'name': 'giant robot'}, {'id': 11479, 'name': 'social commentary'}, {'id': 12999, 'name': 'black and white'}, {'id': 162365, 'name': 'military'}, {'id': 199065, 'name': 'physics professor'}, {'id': 202647, 'name': 'humanity'}, {'id': 231277, 'name': 'alien technology'}, {'id': 236401, 'name': 'mathematical equation'}]"
  },
  {
    "id": 32670,
    "movie_id": 3063,
    "genres": "[{'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 23969,
    "overview": "Rufus T. Firefly is named president/dictator of bankrupt Freedonia and declares war on neighboring Sylvania over the love of wealthy Mrs. Teasdale.",
    "popularity": "6.819957",
    "score": 8,
    "title": "Duck Soup (1933)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmYxZGU2NWYtNzQxZS00NmEyLWIzN2YtMDk5MWM0ODc5ZTE4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX182_CR0",
    "keywords": "[{'id': 407, 'name': 'dictator'}, {'id': 470, 'name': 'spy'}, {'id': 1704, 'name': 'ambassador'}, {'id': 4063, 'name': 'siege'}, {'id': 4129, 'name': 'widow'}, {'id': 9253, 'name': 'slapstick'}, {'id': 11333, 'name': 'cigar smoking'}, {'id': 11372, 'name': 'lemonade'}, {'id': 46951, 'name': 'mirror'}, {'id': 155707, 'name': 'musical number'}, {'id': 162752, 'name': 'dowager'}, {'id': 220648, 'name': 'geofiction'}]"
  },
  {
    "id": 32671,
    "movie_id": 13667,
    "genres": "[{'id': 35, 'name': 'Comedy'}]",
    "imdb_id": 88794,
    "overview": "Lane Meyer is obsessed with his girlfriend Beth and is crushed when she falls for the new captain of the ski team, Roy. After several failed suicide attempts, narrow escapes from the relentless paper boy, and nearly unbearable dinners at home with his crazy family, Lane finds a new love in French exchange student Monique Junot. Meanwhile, he must beat Roy on the slopes to regain his honor.",
    "popularity": "8.994189",
    "score": 7.2,
    "title": "Better Off Dead... (1985)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzRmMjE0MzMtZmQzYi00NjQ1LTk5ODgtYWEzZDViODkxNWFjXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_UX182_CR0",
    "keywords": "[{'id': 1339, 'name': 'duck'}, {'id': 5801, 'name': 'nerd'}, {'id': 7074, 'name': 'paperboy'}, {'id': 159558, 'name': 'skiing'}, {'id': 179430, 'name': 'aftercreditsstinger'}, {'id': 179431, 'name': 'duringcreditsstinger'}]"
  },
  {
    "id": 32672,
    "movie_id": 694,
    "genres": "[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]",
    "imdb_id": 81505,
    "overview": "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
    "popularity": "19.611589",
    "score": 8.4,
    "title": "The Shining (1980)",
    "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0",
    "keywords": "[{'id': 612, 'name': 'hotel'}, {'id': 1533, 'name': 'isolation'}, {'id': 1611, 'name': 'hotelier'}, {'id': 1981, 'name': 'colorado'}, {'id': 2158, 'name': 'maze'}, {'id': 3458, 'name': 'bartender'}, {'id': 3598, 'name': 'ax'}, {'id': 6262, 'name': 'delusion'}, {'id': 9957, 'name': 'loneliness'}, {'id': 10241, 'name': 'caretaker'}, {'id': 10629, 'name': 'vision'}, {'id': 10794, 'name': 'snow'}, {'id': 13028, 'name': 'writer'}, {'id': 33457, 'name': 'alcoholic'}, {'id': 190107, 'name': 'snowed in'}, {'id': 198471, 'name': 'off season'}]"
  }]

  module.exports = {dummy}